apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: samtykke-api
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 8080
  replicas:
    cpuThresholdPercentage: 90
    min: 1
    max: 1
  liveness:
    initialDelay: 30
    path: isalive
  readiness:
    initialDelay: 30
    path: isready
  resources:
    limits:
      cpu: 400m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: samtykke
            envVarPrefix: DB
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
  env:
    - name: PDFGEN_URL
      value: http://samtykke-pdfgen.team-researchops
  accessPolicy:
    inbound:
      rules:
        - application: samtykke-employee
        - application: samtykke-citizen
    outbound:
      rules:
        - application: samtykke-pdfgen