apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: samtykke-api
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{ image }}
  port: 8080
  replicas:
    cpuThresholdPercentage: 90
    min: 1
    max: 1
  liveness:
    initialDelay: 30
    path: isalive
  readiness:
    initialDelay: 30
    path: isready
  accessPolicy:
    inbound:
      rules:
        - application: samtykke-citizen
        - application: samtykke-employee